# Combined additive-plus-proportional one-compartment PK benchmark.
ENV["FLIPFLOP_JULIA_RESIDUAL_MODEL"] = "combined"
ENV["FLIPFLOP_JULIA_SUBJECTS_CSV"] = get(ENV, "FLIPFLOP_JULIA_SUBJECTS_CSV", "")
ENV["FLIPFLOP_JULIA_STARTS_CSV"] = get(ENV, "FLIPFLOP_JULIA_STARTS_CSV", "")
ENV["FLIPFLOP_JULIA_OUTDIR"] = get(ENV, "FLIPFLOP_JULIA_OUTDIR", joinpath(@__DIR__, "outputs", "flipflop"))
ENV["FLIPFLOP_JULIA_METHODS"] = get(ENV, "FLIPFLOP_JULIA_METHODS", "FULL_IMPLICIT,FULL_UNROLL_1NEWTON,STOP,FD")
ENV["FLIPFLOP_JULIA_LOGDET_MODE"] = get(ENV, "FLIPFLOP_JULIA_LOGDET_MODE", "raw")
ENV["FLIPFLOP_JULIA_N_SUBJ"] = get(ENV, "FLIPFLOP_JULIA_N_SUBJ", "50")
ENV["FLIPFLOP_JULIA_N_STARTS"] = get(ENV, "FLIPFLOP_JULIA_N_STARTS", "100")
ENV["FLIPFLOP_JULIA_MAXITER_ETA"] = get(ENV, "FLIPFLOP_JULIA_MAXITER_ETA", "40")
include(joinpath(@__DIR__, "src", "flipflop_multistart_methods.jl"))
main()