"""Generate model-specific analytic sensitivity-ODE coefficients.

This is a build-time utility only.  It uses SymPy's symbolic differentiation
to emit ordinary Julia/Float64 expressions for the model right-hand sides and
their first and second partial derivatives.  The generated Julia code has no
SymPy or AD dependency at run time.
"""

from __future__ import annotations

from pathlib import Path
import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src"


def _emit_assignments(name: str, expressions: list[tuple[str, sp.Expr]]) -> list[str]:
    """Emit a CSE-reduced sequence of Julia assignments for nonzero entries."""
    kept = [(target, sp.expand(expr)) for target, expr in expressions if expr != 0]
    if not kept:
        return []
    replacements, reduced = sp.cse(
        [expr for _, expr in kept], symbols=sp.numbered_symbols("tmp"), optimizations="basic"
    )
    lines = []
    for symbol, expr in replacements:
        lines.append(f"    {symbol} = {sp.julia_code(expr)}")
    for (target, _), expr in zip(kept, reduced):
        lines.append(f"    {target} = {sp.julia_code(expr)}")
    return lines


def generate_fk() -> None:
    x = sp.symbols("x1:9")
    u = sp.symbols("u1:17")  # theta structural 1:9, then eta 1:7
    cl = sp.exp(u[0] + u[9])
    q = sp.exp(u[1] + u[10])
    v1 = sp.exp(u[2] + u[11])
    v2 = sp.exp(u[3] + u[12])
    ka = sp.exp(u[4])
    mtt = sp.exp(u[5] + u[13])
    circ0 = sp.exp(u[6] + u[14])
    gamma = sp.exp(u[7])
    alpha = sp.exp(u[8] + u[15])
    k10 = cl / v1
    k12 = q / v1
    k21 = q / v2
    ktr = sp.Integer(4) / mtt
    conc = x[1] / v1
    edrug = alpha * conc
    prol = x[3] + circ0
    tr1 = x[4] + circ0
    tr2 = x[5] + circ0
    tr3 = x[6] + circ0
    circ = x[7] + circ0
    feedback = sp.exp(gamma * sp.log(circ0 / circ))
    f = [
        -ka * x[0],
        ka * x[0] - (k10 + k12) * x[1] + k21 * x[2],
        k12 * x[1] - k21 * x[2],
        ktr * prol * ((1 - edrug) * feedback - 1),
        ktr * (prol - tr1),
        ktr * (tr1 - tr2),
        ktr * (tr2 - tr3),
        ktr * (tr3 - circ),
    ]
    # The literal sensitivity system needs eta--eta and eta--theta second
    # derivatives, but never theta--theta state sensitivities.  Emitting only
    # those blocks is faithful to Almquist et al.'s construction and avoids
    # carrying 81 unused theta--theta directions.
    needed_uu = [(a, b) for a in range(10, 17) for b in range(a, 17)]
    needed_uu += [(a, b) for a in range(10, 17) for b in range(1, 10)]
    components: list[list[tuple[str, sp.Expr]]] = []
    for i, expr in enumerate(f, start=1):
        entries: list[tuple[str, sp.Expr]] = [(f"dx[{i}]", expr)]
        for j, var in enumerate(x, start=1):
            entries.append((f"fx[{i}, {j}]", sp.diff(expr, var)))
        for a, var in enumerate(u, start=1):
            entries.append((f"fu[{i}, {a}]", sp.diff(expr, var)))
        for j, left in enumerate(x, start=1):
            for k, right in enumerate(x, start=1):
                entries.append((f"fxx[{i}, {j}, {k}]", sp.diff(expr, left, right)))
        for j, left in enumerate(x, start=1):
            for a, right in enumerate(u, start=1):
                entries.append((f"fxu[{i}, {j}, {a}]", sp.diff(expr, left, right)))
        for a, b in needed_uu:
            entries.append((f"fuu[{i}, {a}, {b}]", sp.diff(expr, u[a - 1], u[b - 1])))
        components.append(entries)
    lines = [
        "# This file is generated by scripts/generate_almquist_sensitivity_ode_derivatives.py.",
        "# Do not edit by hand; it contains analytic derivatives of the FK ODE RHS.",
    ]
    for i, entries in enumerate(components, start=1):
        lines.extend([
            f"Base.@noinline function fk_rhs_sensitivity_component_{i}!(dx, fx, fu, fxx, fxu, fuu, x, u)",
            "    x1, x2, x3, x4, x5, x6, x7, x8 = x",
            "    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u",
        ])
        lines.extend(_emit_assignments("fk", entries))
        lines.extend(["    return nothing", "end", ""])
    lines.extend([
        "function fk_rhs_sensitivity_derivatives(x::Vector{Float64}, u::Vector{Float64})",
        "    length(x) == 8 || error(\"FK state must have length 8\")",
        "    length(u) == 16 || error(\"FK structural sensitivity vector must have length 16\")",
        "    dx = zeros(8)",
        "    fx = zeros(8, 8)",
        "    fu = zeros(8, 16)",
        "    fxx = zeros(8, 8, 8)",
        "    fxu = zeros(8, 8, 16)",
        "    fuu = zeros(8, 16, 16)",
    ])
    for i in range(1, 9):
        lines.append(f"    fk_rhs_sensitivity_component_{i}!(dx, fx, fu, fxx, fxu, fuu, x, u)")
    lines.extend(["    return dx, fx, fu, fxx, fxu, fuu", "end", ""])
    (OUT / "generated_fk_sensitivity_derivatives.jl").write_text("\n".join(lines), encoding="utf-8")


def generate_warfarin() -> None:
    # Eight ODE-relevant log-parameter directions:
    # theta KA, CL, V, KE0, eta KA, CL, V, KE0.
    t, dose, ce = sp.symbols("t dose ce")
    w = sp.symbols("w1:9")
    ka = sp.exp(w[0] + w[4])
    cl = sp.exp(w[1] + w[5])
    v = sp.exp(w[2] + w[6])
    ke0 = sp.exp(w[3] + w[7])
    k = cl / v
    cp = dose / v * ka * (sp.exp(-k * t) - sp.exp(-ka * t)) / (ka - k)
    rhs = ke0 * (cp - ce)
    entries: list[tuple[str, sp.Expr]] = [("cp", cp), ("f", rhs), ("fc", sp.diff(rhs, ce))]
    for a, var in enumerate(w, start=1):
        entries.append((f"cpw[{a}]", sp.diff(cp, var)))
        entries.append((f"fw[{a}]", sp.diff(rhs, var)))
        entries.append((f"fcw[{a}]", sp.diff(rhs, ce, var)))
        for b, other in enumerate(w, start=1):
            entries.append((f"cpww[{a}, {b}]", sp.diff(cp, var, other)))
            entries.append((f"fww[{a}, {b}]", sp.diff(rhs, var, other)))
    lines = [
        "# This file is generated by scripts/generate_almquist_sensitivity_ode_derivatives.py.",
        "# Analytic coefficients for the warfarin effect-compartment sensitivity ODE.",
        "function warfarin_ce_rhs_sensitivity_derivatives(t::Float64, dose::Float64, ce::Float64, w::Vector{Float64})",
        "    length(w) == 8 || error(\"warfarin ODE sensitivity vector must have length 8\")",
        "    w1, w2, w3, w4, w5, w6, w7, w8 = w",
        "    cpw = zeros(8)",
        "    cpww = zeros(8, 8)",
        "    fw = zeros(8)",
        "    fcw = zeros(8)",
        "    fww = zeros(8, 8)",
    ]
    lines.extend(_emit_assignments("warfarin-ce", entries))
    lines.extend(["    return cp, cpw, cpww, f, fc, fw, fcw, fww", "end", ""])

    # Full structural directions, with EMAX optionally carrying IIV:
    # theta KA,CL,V,E0,C50,KE0,logit EMAX, then eta KA,CL,V,E0,C50,KE0,EMAX.
    c = sp.symbols("c")
    z = sp.symbols("z1:15")
    e0 = sp.exp(z[3] + z[10])
    c50 = sp.exp(z[4] + z[11])
    ke0_unused = z[5] + z[12]  # keeps the intended coordinate declaration explicit
    emax = 1 / (1 + sp.exp(-(z[6] + z[13])))
    pd = e0 * (1 - emax * c / (c50 + c + sp.Float("1e-12")))
    entries = [("value", pd), ("dc", sp.diff(pd, c)), ("dcc", sp.diff(pd, c, c))]
    for a, var in enumerate(z, start=1):
        entries.append((f"dw[{a}]", sp.diff(pd, var)))
        entries.append((f"dcw[{a}]", sp.diff(pd, c, var)))
        for b, other in enumerate(z, start=1):
            entries.append((f"dww[{a}, {b}]", sp.diff(pd, var, other)))
    lines.extend([
        "function warfarin_pd_output_derivatives(ce::Float64, z::Vector{Float64})",
        "    length(z) == 14 || error(\"warfarin structural vector must have length 14\")",
        "    z1, z2, z3, z4, z5, z6, z7, z8, z9, z10, z11, z12, z13, z14 = z",
        "    c = ce",
        "    dw = zeros(14)",
        "    dcw = zeros(14)",
        "    dww = zeros(14, 14)",
    ])
    lines.extend(_emit_assignments("warfarin-pd", entries))
    lines.extend(["    return value, dc, dw, dcc, dcw, dww", "end", ""])
    (OUT / "generated_warfarin_sensitivity_derivatives.jl").write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    generate_fk()
    generate_warfarin()
    print("Generated analytic FK and warfarin sensitivity coefficients.")
