# This file is generated by scripts/generate_almquist_sensitivity_ode_derivatives.py.
# Do not edit by hand; it contains analytic derivatives of the FK ODE RHS.
Base.@noinline function fk_rhs_sensitivity_component_1!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = exp(u5)
    tmp1 = -tmp0 .* x1
    tmp2 = -tmp0
    dx[1] = tmp1
    fx[1, 1] = tmp2
    fu[1, 5] = tmp1
    fxu[1, 1, 5] = tmp2
    return nothing
end

Base.@noinline function fk_rhs_sensitivity_component_2!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = exp(u5)
    tmp1 = tmp0 .* x1
    tmp2 = exp(u11) .* exp(u2)
    tmp3 = exp(-u13)
    tmp4 = exp(-u4)
    tmp5 = tmp3 .* tmp4
    tmp6 = tmp2 .* tmp5 .* x3
    tmp7 = exp(u1) .* exp(u10)
    tmp8 = exp(-u12) .* exp(-u3)
    tmp9 = tmp8 .* x2
    tmp10 = tmp7 .* tmp9
    tmp11 = -tmp10
    tmp12 = tmp2 .* tmp9
    tmp13 = tmp8 .* (tmp2 + tmp7)
    tmp14 = tmp2 .* tmp5
    tmp15 = tmp2 .* (tmp3 .* tmp4 .* x3 - tmp9)
    tmp16 = tmp13 .* x2
    tmp17 = -tmp6
    tmp18 = -tmp7 .* tmp8
    tmp19 = -tmp2 .* tmp8
    tmp20 = -tmp14
    tmp21 = -tmp16
    dx[2] = tmp1 + tmp11 - tmp12 + tmp6
    fx[2, 1] = tmp0
    fx[2, 2] = -tmp13
    fx[2, 3] = tmp14
    fu[2, 1] = tmp11
    fu[2, 2] = tmp15
    fu[2, 3] = tmp16
    fu[2, 4] = tmp17
    fu[2, 5] = tmp1
    fu[2, 10] = tmp11
    fu[2, 11] = tmp15
    fu[2, 12] = tmp16
    fu[2, 13] = tmp17
    fxu[2, 1, 5] = tmp0
    fxu[2, 2, 1] = tmp18
    fxu[2, 2, 2] = tmp19
    fxu[2, 2, 3] = tmp13
    fxu[2, 2, 10] = tmp18
    fxu[2, 2, 11] = tmp19
    fxu[2, 2, 12] = tmp13
    fxu[2, 3, 2] = tmp14
    fxu[2, 3, 4] = tmp20
    fxu[2, 3, 11] = tmp14
    fxu[2, 3, 13] = tmp20
    fuu[2, 10, 10] = tmp11
    fuu[2, 10, 12] = tmp10
    fuu[2, 11, 11] = tmp15
    fuu[2, 11, 12] = tmp12
    fuu[2, 11, 13] = tmp17
    fuu[2, 12, 12] = tmp21
    fuu[2, 13, 13] = tmp6
    fuu[2, 10, 1] = tmp11
    fuu[2, 10, 3] = tmp10
    fuu[2, 11, 2] = tmp15
    fuu[2, 11, 3] = tmp12
    fuu[2, 11, 4] = tmp17
    fuu[2, 12, 1] = tmp10
    fuu[2, 12, 2] = tmp12
    fuu[2, 12, 3] = tmp21
    fuu[2, 13, 2] = tmp17
    fuu[2, 13, 4] = tmp6
    return nothing
end

Base.@noinline function fk_rhs_sensitivity_component_3!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = exp(-u12) .* exp(-u3)
    tmp1 = tmp0 .* x2
    tmp2 = exp(-u13) .* exp(-u4)
    tmp3 = tmp2 .* x3
    tmp4 = exp(u11) .* exp(u2)
    tmp5 = tmp4 .* (tmp1 - tmp3)
    tmp6 = tmp0 .* tmp4
    tmp7 = tmp2 .* tmp4
    tmp8 = -tmp7
    tmp9 = tmp1 .* tmp4
    tmp10 = -tmp9
    tmp11 = tmp3 .* tmp4
    tmp12 = -tmp6
    tmp13 = -tmp11
    dx[3] = tmp5
    fx[3, 2] = tmp6
    fx[3, 3] = tmp8
    fu[3, 2] = tmp5
    fu[3, 3] = tmp10
    fu[3, 4] = tmp11
    fu[3, 11] = tmp5
    fu[3, 12] = tmp10
    fu[3, 13] = tmp11
    fxu[3, 2, 2] = tmp6
    fxu[3, 2, 3] = tmp12
    fxu[3, 2, 11] = tmp6
    fxu[3, 2, 12] = tmp12
    fxu[3, 3, 2] = tmp8
    fxu[3, 3, 4] = tmp7
    fxu[3, 3, 11] = tmp8
    fxu[3, 3, 13] = tmp7
    fuu[3, 11, 11] = tmp5
    fuu[3, 11, 12] = tmp10
    fuu[3, 11, 13] = tmp11
    fuu[3, 12, 12] = tmp9
    fuu[3, 13, 13] = tmp13
    fuu[3, 11, 2] = tmp5
    fuu[3, 11, 3] = tmp10
    fuu[3, 11, 4] = tmp11
    fuu[3, 12, 2] = tmp10
    fuu[3, 12, 3] = tmp9
    fuu[3, 13, 2] = tmp11
    fuu[3, 13, 4] = tmp13
    return nothing
end

Base.@noinline function fk_rhs_sensitivity_component_4!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = exp(u8)
    tmp1 = exp(u15)
    tmp2 = exp(u7)
    tmp3 = tmp1 .* tmp2
    tmp4 = 1 ./ (tmp3 + x8)
    tmp5 = tmp3 .* tmp4
    tmp6 = log(tmp5)
    tmp7 = tmp0 .* tmp6
    tmp8 = exp(tmp7)
    tmp9 = tmp8 .* x4
    tmp10 = exp(u16)
    tmp11 = exp(u9)
    tmp12 = exp(-u12)
    tmp13 = exp(-u3)
    tmp14 = tmp10 .* tmp11 .* tmp12 .* tmp13
    tmp15 = tmp14 .* x2
    tmp16 = tmp3 + x4
    tmp17 = tmp3 .* tmp8
    tmp18 = tmp15 .* tmp17 - tmp17
    tmp19 = tmp15 .* tmp9 + tmp16 + tmp18 - tmp8 .* x4
    tmp20 = 4 * exp(-u14) .* exp(-u6)
    tmp21 = -tmp19 .* tmp20
    tmp22 = tmp20 .* tmp8
    tmp23 = tmp14 .* tmp22
    tmp24 = tmp16 .* tmp23
    tmp25 = -tmp24
    tmp26 = tmp15 .* tmp8
    tmp27 = tmp26 - tmp8 + 1
    tmp28 = tmp15 .* tmp3 + tmp15 .* x4 - tmp3 - x4
    tmp29 = tmp0 .* tmp8
    tmp30 = tmp20 .* tmp29
    tmp31 = tmp30 .* tmp4
    tmp32 = tmp20 .* tmp26
    tmp33 = tmp16 .* tmp32
    tmp34 = tmp19 .* tmp20
    tmp35 = exp(2 * u15)
    tmp36 = exp(2 * u7)
    tmp37 = tmp35 .* tmp36
    tmp38 = 1 ./ (2 * tmp3 .* x8 + tmp37 + x8 .^ 2)
    tmp39 = tmp29 .* tmp38
    tmp40 = exp(3 * u15)
    tmp41 = exp(3 * u7)
    tmp42 = tmp40 .* tmp41
    tmp43 = tmp39 .* tmp42
    tmp44 = tmp37 .* tmp38
    tmp45 = tmp0 .* tmp9
    tmp46 = tmp44 .* tmp45
    tmp47 = tmp0 .* tmp44
    tmp48 = tmp45 .* tmp5
    tmp49 = tmp0 .* tmp3
    tmp50 = tmp37 .* tmp4
    tmp51 = tmp0 .* tmp50 .* tmp8
    tmp52 = tmp15 .* tmp51
    tmp53 = tmp15 .* tmp43
    tmp54 = tmp15 .* tmp48
    tmp55 = tmp0 .* tmp5
    tmp56 = tmp15 .* tmp46
    tmp57 = tmp18 + tmp3
    tmp58 = tmp20 .* (tmp0 .* tmp1 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp2 .* tmp38 .* tmp8 .* x2 .* x4 .* x8 + tmp0 .* tmp1 .* tmp2 .* tmp4 .* tmp8 .* x8 + tmp0 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp35 .* tmp36 .* tmp38 .* tmp8 .* x2 .* x8 + tmp0 .* tmp35 .* tmp36 .* tmp4 .* tmp8 + tmp0 .* tmp4 .* tmp8 .* x4 .* x8 - tmp15 .* tmp4 .* tmp45 .* x8 - tmp26 .* tmp55 .* x8 - tmp38 .* tmp49 .* tmp9 .* x8 - tmp43 - tmp46 - tmp47 .* tmp8 .* x8 + tmp48 - tmp52 + tmp53 - tmp54 + tmp56 - tmp57)
    tmp59 = -tmp28
    tmp60 = tmp22 .* tmp7
    tmp61 = -tmp33
    tmp62 = -tmp23
    tmp63 = tmp14 .* tmp16
    tmp64 = tmp31 .* tmp63
    tmp65 = tmp15 - 1
    tmp66 = tmp31 .* tmp65
    tmp67 = tmp0 .* x4
    tmp68 = -tmp0 .* tmp1 .* tmp2 .* tmp4 .* x4 - tmp0 .* tmp35 .* tmp36 .* tmp4 + tmp3 + tmp49 + tmp67
    tmp69 = -tmp68
    tmp70 = tmp23 .* tmp69
    tmp71 = tmp20 .* tmp27
    tmp72 = -tmp1 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp2 .* tmp4 .* x2 + tmp5
    tmp73 = tmp30 .* (-tmp65 - tmp72)
    tmp74 = -tmp32
    tmp75 = tmp15 .* tmp16 .* tmp31
    tmp76 = -tmp75
    tmp77 = tmp31 .* tmp59
    tmp78 = tmp3 .* tmp38
    tmp79 = tmp30 .* (tmp0 .* tmp1 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp2 .* tmp4 .* x2 + tmp0 .* tmp1 .* tmp2 .* tmp38 .* x4 + tmp0 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp4 .* x2 .* x4 + tmp0 .* tmp35 .* tmp36 .* tmp38 + tmp1 .* tmp2 .* tmp38 .* x4 - tmp15 .* tmp44 - tmp15 .* tmp47 - tmp15 .* tmp67 .* tmp78 - tmp15 .* tmp78 .* x4 + tmp35 .* tmp36 .* tmp38 - tmp4 .* tmp67 - tmp55 - tmp72)
    tmp80 = tmp7 .* x4
    tmp81 = tmp3 .* tmp7
    tmp82 = tmp15 .* tmp80 + tmp15 .* tmp81 + tmp28 - tmp80 - tmp81
    tmp83 = tmp32 .* tmp68
    tmp84 = tmp0 .* tmp17
    tmp85 = tmp48 - tmp54 + tmp57
    tmp86 = tmp20 .* (tmp15 .* tmp45 + tmp15 .* tmp84 - tmp45 + tmp51 - tmp52 - tmp84 + tmp85)
    tmp87 = exp(2 * u8)
    tmp88 = tmp8 .* tmp87
    tmp89 = tmp87 .* tmp9
    tmp90 = tmp20 .* (2 * tmp0 .* tmp1 .* tmp2 .* tmp8 + 3 * tmp0 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp35 .* tmp36 .* tmp4 .* tmp8 .* x2 + 2 * tmp1 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp2 .* tmp4 .* tmp8 .* tmp87 .* x2 .* x4 + tmp1 .* tmp2 .* tmp8 .* tmp87 + 2 * tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp35 .* tmp36 .* tmp4 .* tmp8 .* tmp87 .* x2 - tmp15 .* tmp17 .* tmp87 - tmp15 .* tmp38 .* tmp42 .* tmp88 - tmp15 .* tmp44 .* tmp89 - 2 * tmp15 .* tmp84 - tmp15 .* tmp89 + tmp35 .* tmp36 .* tmp38 .* tmp8 .* tmp87 .* x4 + tmp38 .* tmp40 .* tmp41 .* tmp8 .* tmp87 + tmp43 + tmp46 - 2 * tmp5 .* tmp89 - 2 * tmp50 .* tmp88 - 3 * tmp51 - tmp53 - tmp56 + tmp8 .* tmp87 .* x4 - tmp85)
    tmp91 = tmp32 .* tmp69
    tmp92 = tmp33 .* tmp7
    dx[4] = tmp21
    fx[4, 2] = tmp25
    fx[4, 4] = -tmp20 .* tmp27
    fx[4, 8] = tmp28 .* tmp31
    fu[4, 3] = tmp33
    fu[4, 6] = tmp34
    fu[4, 7] = tmp58
    fu[4, 8] = tmp59 .* tmp60
    fu[4, 9] = tmp61
    fu[4, 12] = tmp33
    fu[4, 14] = tmp34
    fu[4, 15] = tmp58
    fu[4, 16] = tmp61
    fxx[4, 2, 4] = tmp62
    fxx[4, 2, 8] = tmp64
    fxx[4, 4, 2] = tmp62
    fxx[4, 4, 8] = tmp66
    fxx[4, 8, 2] = tmp64
    fxx[4, 8, 4] = tmp66
    fxx[4, 8, 8] = tmp20 .* tmp39 .* (-tmp15 .* tmp49 - tmp15 .* tmp67 - tmp28 + tmp49 + tmp67)
    fxu[4, 2, 3] = tmp24
    fxu[4, 2, 6] = tmp24
    fxu[4, 2, 7] = tmp70
    fxu[4, 2, 8] = -tmp60 .* tmp63
    fxu[4, 2, 9] = tmp25
    fxu[4, 2, 12] = tmp24
    fxu[4, 2, 14] = tmp24
    fxu[4, 2, 15] = tmp70
    fxu[4, 2, 16] = tmp25
    fxu[4, 4, 3] = tmp32
    fxu[4, 4, 6] = tmp71
    fxu[4, 4, 7] = tmp73
    fxu[4, 4, 8] = -tmp60 .* tmp65
    fxu[4, 4, 9] = tmp74
    fxu[4, 4, 12] = tmp32
    fxu[4, 4, 14] = tmp71
    fxu[4, 4, 15] = tmp73
    fxu[4, 4, 16] = tmp74
    fxu[4, 8, 3] = tmp76
    fxu[4, 8, 6] = tmp77
    fxu[4, 8, 7] = tmp79
    fxu[4, 8, 8] = tmp31 .* tmp82
    fxu[4, 8, 9] = tmp75
    fxu[4, 8, 12] = tmp76
    fxu[4, 8, 14] = tmp77
    fxu[4, 8, 15] = tmp79
    fxu[4, 8, 16] = tmp75
    fuu[4, 12, 12] = tmp61
    fuu[4, 12, 14] = tmp61
    fuu[4, 12, 15] = tmp83
    fuu[4, 12, 16] = tmp33
    fuu[4, 14, 14] = tmp21
    fuu[4, 14, 15] = tmp86
    fuu[4, 14, 16] = tmp33
    fuu[4, 15, 15] = tmp90
    fuu[4, 15, 16] = tmp91
    fuu[4, 16, 16] = tmp61
    fuu[4, 12, 3] = tmp61
    fuu[4, 12, 6] = tmp61
    fuu[4, 12, 7] = tmp83
    fuu[4, 12, 8] = tmp92
    fuu[4, 12, 9] = tmp33
    fuu[4, 14, 3] = tmp61
    fuu[4, 14, 6] = tmp21
    fuu[4, 14, 7] = tmp86
    fuu[4, 14, 8] = tmp28 .* tmp60
    fuu[4, 14, 9] = tmp33
    fuu[4, 15, 3] = tmp83
    fuu[4, 15, 6] = tmp86
    fuu[4, 15, 7] = tmp90
    fuu[4, 15, 8] = tmp30 .* (tmp0 .* tmp1 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp2 .* tmp4 .* tmp6 .* x2 .* x4 + tmp0 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp35 .* tmp36 .* tmp4 .* tmp6 .* x2 + tmp1 .* tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp2 .* tmp4 .* x2 .* x4 + tmp1 .* tmp2 .* tmp6 + tmp10 .* tmp11 .* tmp12 .* tmp13 .* tmp35 .* tmp36 .* tmp4 .* x2 - tmp15 .* tmp3 .* tmp6 - tmp5 .* tmp80 - tmp5 .* x4 - tmp50 .* tmp7 - tmp50 - tmp82)
    fuu[4, 15, 9] = tmp91
    fuu[4, 16, 3] = tmp33
    fuu[4, 16, 6] = tmp33
    fuu[4, 16, 7] = tmp91
    fuu[4, 16, 8] = -tmp92
    fuu[4, 16, 9] = tmp61
    return nothing
end

Base.@noinline function fk_rhs_sensitivity_component_5!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = x4 - x5
    tmp1 = 4 * exp(-u14) .* exp(-u6)
    tmp2 = tmp0 .* tmp1
    tmp3 = -tmp1
    tmp4 = -tmp0 .* tmp1
    dx[5] = tmp2
    fx[5, 4] = tmp1
    fx[5, 5] = tmp3
    fu[5, 6] = tmp4
    fu[5, 14] = tmp4
    fxu[5, 4, 6] = tmp3
    fxu[5, 4, 14] = tmp3
    fxu[5, 5, 6] = tmp1
    fxu[5, 5, 14] = tmp1
    fuu[5, 14, 14] = tmp2
    fuu[5, 14, 6] = tmp2
    return nothing
end

Base.@noinline function fk_rhs_sensitivity_component_6!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = x5 - x6
    tmp1 = 4 * exp(-u14) .* exp(-u6)
    tmp2 = tmp0 .* tmp1
    tmp3 = -tmp1
    tmp4 = -tmp0 .* tmp1
    dx[6] = tmp2
    fx[6, 5] = tmp1
    fx[6, 6] = tmp3
    fu[6, 6] = tmp4
    fu[6, 14] = tmp4
    fxu[6, 5, 6] = tmp3
    fxu[6, 5, 14] = tmp3
    fxu[6, 6, 6] = tmp1
    fxu[6, 6, 14] = tmp1
    fuu[6, 14, 14] = tmp2
    fuu[6, 14, 6] = tmp2
    return nothing
end

Base.@noinline function fk_rhs_sensitivity_component_7!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = x6 - x7
    tmp1 = 4 * exp(-u14) .* exp(-u6)
    tmp2 = tmp0 .* tmp1
    tmp3 = -tmp1
    tmp4 = -tmp0 .* tmp1
    dx[7] = tmp2
    fx[7, 6] = tmp1
    fx[7, 7] = tmp3
    fu[7, 6] = tmp4
    fu[7, 14] = tmp4
    fxu[7, 6, 6] = tmp3
    fxu[7, 6, 14] = tmp3
    fxu[7, 7, 6] = tmp1
    fxu[7, 7, 14] = tmp1
    fuu[7, 14, 14] = tmp2
    fuu[7, 14, 6] = tmp2
    return nothing
end

Base.@noinline function fk_rhs_sensitivity_component_8!(dx, fx, fu, fxx, fxu, fuu, x, u)
    x1, x2, x3, x4, x5, x6, x7, x8 = x
    u1, u2, u3, u4, u5, u6, u7, u8, u9, u10, u11, u12, u13, u14, u15, u16 = u
    tmp0 = x7 - x8
    tmp1 = 4 * exp(-u14) .* exp(-u6)
    tmp2 = tmp0 .* tmp1
    tmp3 = -tmp1
    tmp4 = -tmp0 .* tmp1
    dx[8] = tmp2
    fx[8, 7] = tmp1
    fx[8, 8] = tmp3
    fu[8, 6] = tmp4
    fu[8, 14] = tmp4
    fxu[8, 7, 6] = tmp3
    fxu[8, 7, 14] = tmp3
    fxu[8, 8, 6] = tmp1
    fxu[8, 8, 14] = tmp1
    fuu[8, 14, 14] = tmp2
    fuu[8, 14, 6] = tmp2
    return nothing
end

function fk_rhs_sensitivity_derivatives(x::Vector{Float64}, u::Vector{Float64})
    length(x) == 8 || error("FK state must have length 8")
    length(u) == 16 || error("FK structural sensitivity vector must have length 16")
    dx = zeros(8)
    fx = zeros(8, 8)
    fu = zeros(8, 16)
    fxx = zeros(8, 8, 8)
    fxu = zeros(8, 8, 16)
    fuu = zeros(8, 16, 16)
    fk_rhs_sensitivity_component_1!(dx, fx, fu, fxx, fxu, fuu, x, u)
    fk_rhs_sensitivity_component_2!(dx, fx, fu, fxx, fxu, fuu, x, u)
    fk_rhs_sensitivity_component_3!(dx, fx, fu, fxx, fxu, fuu, x, u)
    fk_rhs_sensitivity_component_4!(dx, fx, fu, fxx, fxu, fuu, x, u)
    fk_rhs_sensitivity_component_5!(dx, fx, fu, fxx, fxu, fuu, x, u)
    fk_rhs_sensitivity_component_6!(dx, fx, fu, fxx, fxu, fuu, x, u)
    fk_rhs_sensitivity_component_7!(dx, fx, fu, fxx, fxu, fuu, x, u)
    fk_rhs_sensitivity_component_8!(dx, fx, fu, fxx, fxu, fuu, x, u)
    return dx, fx, fu, fxx, fxu, fuu
end
